Cards
turntabl/turntabl-developer-access-control pull request #2
Opened 2020-01-29 22:43 UTC by patriciakasapa

2020-01-29 23:06 UTC, sammoorhouse commented
I think Heroku review apps will be useful for reviewing UI changes: https://devcenter.heroku.com/articles/github-integration-review-apps

2020-01-30 10:55 UTC, patriciakasapa commented
https://turntabl-dev-cards-yroaeklcq7n.herokuapp.com/

2020-02-07 10:25 UTC, sammoorhouse requested changes

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +    keys: ["super secret"],
can we do better than this please

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      // cert: process.env.CERTIFICATE
what do these comments mean?

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      console.log("profile", profile);
can you remove this console log?

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +let userEmail = "";
this should not be a server-side global

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      protocol: "https://",
remove these comments and add your own

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      // cert: process.env.CERTIFICATE
what does this mean and should we delete it or enable it?

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      // Parse user profile data
this comment doesn't match the code

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      console.log("profile", profile);
remove these console logs

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +      // console.log("assertion", profile.getAssertion.toString());
remove commented code

2020-02-07 10:25 UTC, sammoorhouse commented on server.js
> +    keys: ["super secret"],
what is "super secret" and why are we checking it in to github?

2020-02-07 18:56 UTC, sammoorhouse approved these changes

2020-02-07 18:56 UTC, sammoorhouse commented on server.js
> +    keys: [process.env.SECRET],
Nice

2020-02-07 18:56 UTC, sammoorhouse commented on server.js
> +      // SSO URL to load the server.js to get the various module exports after authentication.
Not really sure what this means, it doesn’t have much to do with modules...

2020-02-07 21:30 UTC, merged